// AUTO-GENERATED by build.py — do not edit by hand.
// Re-run `python3 build.py` to regenerate from Data/.
const players = {
  "autry": {
    "name": "Trey Autry",
    "number": 0,
    "position": "SF·SG",
    "primary_position": "SF",
    "year_abbr": "Jr",
    "year": "Junior",
    "height": "6-4",
    "weight": 210,
    "hometown": "Jamesville, NY",
    "team": "George Washington",
    "season": "2025-26",
    "games": 33,
    "kenpom": {
      "minPct": 69.7,
      "ortg": 125.4,
      "possPct": 15.4,
      "shotsPct": 18.9,
      "efg": 57.9,
      "ts": 60.5,
      "orPct": 3.2,
      "drPct": 11.3,
      "aRate": 8.4,
      "toRate": 11.7,
      "blkPct": 0.8,
      "stlPct": 1.4,
      "fc40": 3.5,
      "fd40": 2.3,
      "ftRate": 21.4,
      "ft": {
        "made": 47,
        "att": 58,
        "pct": 0.81
      },
      "twoP": {
        "made": 34,
        "att": 57,
        "pct": 0.596
      },
      "threeP": {
        "made": 82,
        "att": 214,
        "pct": 0.38
      }
    },
    "playTypes": [
      {
        "name": "Spot Up",
        "poss": 154,
        "timePct": 47.0,
        "pps": 1.24,
        "efg": 59.9,
        "verdict": "Excellent",
        "percentile": 93,
        "subs": [
          {
            "name": "No Dribble Jumper",
            "poss": 128,
            "timePct": 83.1,
            "pps": 1.313,
            "efg": 61.5
          },
          {
            "name": "Drives Right",
            "poss": 6,
            "timePct": 3.9,
            "pps": 1.0,
            "efg": 40.0
          },
          {
            "name": "Drives Left",
            "poss": 13,
            "timePct": 8.4,
            "pps": 0.846,
            "efg": 50.0
          },
          {
            "name": "Drives Straight",
            "poss": 6,
            "timePct": 3.9,
            "pps": 1.0,
            "efg": 62.5
          },
          {
            "name": "Turnover",
            "poss": 1,
            "timePct": 0.6,
            "pps": 0.0,
            "efg": null
          }
        ]
      },
      {
        "name": "Transition",
        "poss": 49,
        "timePct": 14.9,
        "pps": 1.286,
        "efg": 74.4,
        "verdict": "Very Good",
        "percentile": 82,
        "subs": []
      },
      {
        "name": "P&R Ball Handler",
        "poss": 28,
        "timePct": 8.5,
        "pps": 1.107,
        "efg": 54.8,
        "verdict": "Excellent",
        "percentile": 95,
        "subs": []
      },
      {
        "name": "Cut",
        "poss": 22,
        "timePct": 6.7,
        "pps": 1.364,
        "efg": 72.2,
        "verdict": "Very Good",
        "percentile": 76,
        "subs": []
      },
      {
        "name": "Off Screen",
        "poss": 20,
        "timePct": 6.1,
        "pps": 0.75,
        "efg": 38.9,
        "verdict": "Below Average",
        "percentile": 24,
        "subs": []
      },
      {
        "name": "Handoffs",
        "poss": 18,
        "timePct": 5.5,
        "pps": 0.889,
        "efg": 44.4,
        "verdict": "Good",
        "percentile": 54,
        "subs": []
      },
      {
        "name": "Offensive Rebounds (Put Backs)",
        "poss": 13,
        "timePct": 4.0,
        "pps": 1.077,
        "efg": 65.0,
        "verdict": "Average",
        "percentile": 40,
        "subs": []
      },
      {
        "name": "Miscellaneous Plays",
        "poss": 13,
        "timePct": 4.0,
        "pps": 0.308,
        "efg": 0.0,
        "verdict": "Below Average",
        "percentile": 20,
        "subs": []
      },
      {
        "name": "Isolation",
        "poss": 6,
        "timePct": 1.8,
        "pps": 0.0,
        "efg": 0.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "P&R Roll Man",
        "poss": 5,
        "timePct": 1.5,
        "pps": 0.6,
        "efg": 30.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Post-Up",
        "poss": 0,
        "timePct": 0.0,
        "pps": null,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotTypes": [
      {
        "name": "Jump Shot",
        "poss": 223,
        "timePct": 79.9,
        "pps": 1.13,
        "efg": 56.5,
        "verdict": "Excellent",
        "percentile": 88,
        "subs": [
          {
            "name": "Catch and Shoot",
            "poss": 185,
            "timePct": 83.0,
            "pps": 1.15,
            "efg": 57.6,
            "subs": [
              {
                "name": "Guarded",
                "poss": 125,
                "timePct": 67.6,
                "pps": 1.2,
                "efg": 60.0
              },
              {
                "name": "Unguarded",
                "poss": 60,
                "timePct": 32.4,
                "pps": 1.05,
                "efg": 52.5
              }
            ]
          },
          {
            "name": "Dribble Jumper",
            "poss": 36,
            "timePct": 16.1,
            "pps": 1.0,
            "efg": 50.0,
            "subs": []
          },
          {
            "name": "Early Jumper",
            "poss": 2,
            "timePct": 0.9,
            "pps": 0.0,
            "efg": 0.0,
            "subs": []
          }
        ]
      },
      {
        "name": "At Rim",
        "poss": 54,
        "timePct": 19.4,
        "pps": 1.37,
        "efg": 68.5,
        "verdict": "Excellent",
        "percentile": 87,
        "subs": [
          {
            "name": "Layup",
            "poss": 51,
            "timePct": 94.4,
            "pps": 1.37,
            "efg": 68.6,
            "subs": []
          },
          {
            "name": "Dunk",
            "poss": 1,
            "timePct": 1.9,
            "pps": 2.0,
            "efg": 100.0,
            "subs": []
          },
          {
            "name": "Tip",
            "poss": 2,
            "timePct": 3.7,
            "pps": 1.0,
            "efg": 50.0,
            "subs": []
          }
        ]
      },
      {
        "name": "Runner",
        "poss": 2,
        "timePct": 0.7,
        "pps": 0.0,
        "efg": 0.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Hook",
        "poss": 0,
        "timePct": 0.0,
        "pps": null,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotZones": {
      "restrictedArea": {
        "volume": 19.4,
        "efg": 68.5,
        "poss": 54
      },
      "paint": {
        "volume": 0.7,
        "efg": 0.0,
        "poss": 2
      },
      "midrange": {
        "volume": 13.6,
        "efg": 47.4,
        "poss": 38
      },
      "beyondArc": {
        "volume": 66.3,
        "efg": 57.6,
        "poss": 185
      }
    },
    "archetype": "Efficient Off-Ball Scorer",
    "analysis": [
      "High-efficiency low-volume scorer: 125.4 ORtg on just 15.4% usage, 60.5 TS%.",
      "Knockdown shooter: 38.3% from 3 on 214 attempts, 81% from FT.",
      "Plays a complementary role (3.5 FC/40, 2.3 FD/40, 1.4 Stl%); not a creator or defensive disruptor."
    ]
  },
  "hunger": {
    "name": "Luke Hunger",
    "number": 33,
    "position": "C",
    "primary_position": "C",
    "year_abbr": "Sr",
    "year": "Senior",
    "height": "6-10",
    "weight": 250,
    "hometown": "Montreal, QC",
    "team": "George Washington",
    "season": "2025-26",
    "games": 32,
    "kenpom": {
      "minPct": 44.5,
      "ortg": 113.3,
      "possPct": 22.2,
      "shotsPct": 19.8,
      "efg": 53.0,
      "ts": 59.1,
      "orPct": 12.2,
      "drPct": 16.9,
      "aRate": 9.0,
      "toRate": 20.3,
      "blkPct": 0.6,
      "stlPct": 0.6,
      "fc40": 4.3,
      "fd40": 4.3,
      "ftRate": 49.2,
      "ft": {
        "made": 72,
        "att": 89,
        "pct": 0.809
      },
      "twoP": {
        "made": 75,
        "att": 136,
        "pct": 0.551
      },
      "threeP": {
        "made": 14,
        "att": 45,
        "pct": 0.31
      }
    },
    "playTypes": [
      {
        "name": "P&R Roll Man",
        "poss": 66,
        "timePct": 23.7,
        "pps": 0.97,
        "efg": 50.9,
        "verdict": "Average",
        "percentile": 38,
        "subs": []
      },
      {
        "name": "Post-Up",
        "poss": 50,
        "timePct": 18.0,
        "pps": 1.08,
        "efg": 60.7,
        "verdict": "Very Good",
        "percentile": 83,
        "subs": []
      },
      {
        "name": "Cut",
        "poss": 44,
        "timePct": 15.8,
        "pps": 1.159,
        "efg": 61.3,
        "verdict": "Average",
        "percentile": 42,
        "subs": []
      },
      {
        "name": "Offensive Rebounds (Put Backs)",
        "poss": 42,
        "timePct": 15.1,
        "pps": 1.024,
        "efg": 44.8,
        "verdict": "Average",
        "percentile": 32,
        "subs": []
      },
      {
        "name": "Spot Up",
        "poss": 29,
        "timePct": 10.4,
        "pps": 0.828,
        "efg": 50.0,
        "verdict": "Below Average",
        "percentile": 30,
        "subs": [
          {
            "name": "No Dribble Jumper",
            "poss": 15,
            "timePct": 51.7,
            "pps": 1.2,
            "efg": 60.0
          },
          {
            "name": "Drives Right",
            "poss": 6,
            "timePct": 20.7,
            "pps": 0.667,
            "efg": 0.0
          },
          {
            "name": "Drives Left",
            "poss": 5,
            "timePct": 17.2,
            "pps": 0.4,
            "efg": 33.3
          },
          {
            "name": "Drives Straight",
            "poss": 1,
            "timePct": 3.4,
            "pps": 0.0,
            "efg": null
          },
          {
            "name": "Turnover",
            "poss": 2,
            "timePct": 6.9,
            "pps": 0.0,
            "efg": null
          }
        ]
      },
      {
        "name": "Miscellaneous Plays",
        "poss": 20,
        "timePct": 7.2,
        "pps": 0.55,
        "efg": 50.0,
        "verdict": "Good",
        "percentile": 53,
        "subs": []
      },
      {
        "name": "Transition",
        "poss": 16,
        "timePct": 5.8,
        "pps": 0.875,
        "efg": 50.0,
        "verdict": "Below Average",
        "percentile": 19,
        "subs": []
      },
      {
        "name": "Isolation",
        "poss": 5,
        "timePct": 1.8,
        "pps": 1.8,
        "efg": 100.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Handoffs",
        "poss": 4,
        "timePct": 1.4,
        "pps": 1.0,
        "efg": 66.7,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "P&R Ball Handler",
        "poss": 1,
        "timePct": 0.4,
        "pps": 0.0,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Off Screen",
        "poss": 1,
        "timePct": 0.4,
        "pps": 0.0,
        "efg": 0.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotTypes": [
      {
        "name": "Jump Shot",
        "poss": 49,
        "timePct": 26.8,
        "pps": 0.9,
        "efg": 44.9,
        "verdict": "Average",
        "percentile": 42,
        "subs": [
          {
            "name": "Catch and Shoot",
            "poss": 48,
            "timePct": 98.0,
            "pps": 0.88,
            "efg": 43.8,
            "subs": [
              {
                "name": "Guarded",
                "poss": 16,
                "timePct": 33.3,
                "pps": 0.75,
                "efg": 37.5
              },
              {
                "name": "Unguarded",
                "poss": 32,
                "timePct": 66.7,
                "pps": 0.94,
                "efg": 46.9
              }
            ]
          },
          {
            "name": "Dribble Jumper",
            "poss": 1,
            "timePct": 2.0,
            "pps": 2.0,
            "efg": 100.0,
            "subs": []
          },
          {
            "name": "Early Jumper",
            "poss": 0,
            "timePct": 0.0,
            "pps": null,
            "efg": null,
            "subs": []
          }
        ]
      },
      {
        "name": "At Rim",
        "poss": 120,
        "timePct": 65.6,
        "pps": 1.15,
        "efg": 57.5,
        "verdict": "Average",
        "percentile": 50,
        "subs": [
          {
            "name": "Layup",
            "poss": 108,
            "timePct": 90.0,
            "pps": 1.19,
            "efg": 59.3,
            "subs": []
          },
          {
            "name": "Dunk",
            "poss": 3,
            "timePct": 2.5,
            "pps": 2.0,
            "efg": 100.0,
            "subs": []
          },
          {
            "name": "Tip",
            "poss": 9,
            "timePct": 7.5,
            "pps": 0.44,
            "efg": 22.2,
            "subs": []
          }
        ]
      },
      {
        "name": "Runner",
        "poss": 1,
        "timePct": 0.5,
        "pps": 0.0,
        "efg": 0.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Hook",
        "poss": 2,
        "timePct": 1.1,
        "pps": 1.0,
        "efg": 50.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotZones": {
      "restrictedArea": {
        "volume": 69.8,
        "efg": 57.5,
        "poss": 120
      },
      "paint": {
        "volume": 1.7,
        "efg": 33.3,
        "poss": 3
      },
      "midrange": {
        "volume": 0.6,
        "efg": 100.0,
        "poss": 1
      },
      "beyondArc": {
        "volume": 27.9,
        "efg": 43.8,
        "poss": 48
      }
    },
    "archetype": "Rim-Finishing 5",
    "analysis": [
      "Elite finisher (1.20 PPS At Rim, 1.19 Layup on 108 poss).",
      "Featured as P&R Roll Man (23.7%, 66 poss) and Post-Up option (18%, 50 poss).",
      "Willing 3PT shooter (27.9% of attempts, 43.8 eFG).",
      "Elite defensive rebounder (16.9 DR%) — top-rate glass presence.",
      "TO-prone in space (20.3 TORate). Breaks down when forced to put it on the floor outside the paint.",
      "Limited rim protection (0.6 Blk%) reflects scheme more than effort."
    ]
  },
  "slim": {
    "name": "Rafael Castro",
    "number": 30,
    "position": "C",
    "primary_position": "C",
    "year_abbr": "Sr",
    "year": "Senior",
    "height": "6-11",
    "weight": 220,
    "hometown": "Dover, NJ",
    "team": "George Washington",
    "season": "2025-26",
    "games": 28,
    "kenpom": {
      "minPct": 56.7,
      "ortg": 122.4,
      "possPct": 24.9,
      "shotsPct": 20.8,
      "efg": 62.8,
      "ts": 64.7,
      "orPct": 11.8,
      "drPct": 26.3,
      "aRate": 12.7,
      "toRate": 16.0,
      "blkPct": 7.9,
      "stlPct": 3.6,
      "fc40": 2.7,
      "fd40": 6.6,
      "ftRate": 78.1,
      "ft": {
        "made": 125,
        "att": 189,
        "pct": 0.661
      },
      "twoP": {
        "made": 152,
        "att": 242,
        "pct": 0.628
      },
      "threeP": {
        "made": 0,
        "att": 0,
        "pct": 0.0
      }
    },
    "playTypes": [
      {
        "name": "Cut",
        "poss": 92,
        "timePct": 23.5,
        "pps": 1.293,
        "efg": 67.2,
        "verdict": "Good",
        "percentile": 64,
        "subs": []
      },
      {
        "name": "Post-Up",
        "poss": 77,
        "timePct": 19.7,
        "pps": 1.0,
        "efg": 54.3,
        "verdict": "Very Good",
        "percentile": 74,
        "subs": []
      },
      {
        "name": "P&R Roll Man",
        "poss": 68,
        "timePct": 17.4,
        "pps": 1.206,
        "efg": 69.6,
        "verdict": "Very Good",
        "percentile": 73,
        "subs": []
      },
      {
        "name": "Offensive Rebounds (Put Backs)",
        "poss": 57,
        "timePct": 14.6,
        "pps": 1.14,
        "efg": 51.4,
        "verdict": "Good",
        "percentile": 51,
        "subs": []
      },
      {
        "name": "Transition",
        "poss": 39,
        "timePct": 10.0,
        "pps": 1.436,
        "efg": 77.4,
        "verdict": "Excellent",
        "percentile": 94,
        "subs": []
      },
      {
        "name": "Miscellaneous Plays",
        "poss": 21,
        "timePct": 5.4,
        "pps": 0.381,
        "efg": 33.3,
        "verdict": "Below Average",
        "percentile": 29,
        "subs": []
      },
      {
        "name": "Isolation",
        "poss": 16,
        "timePct": 4.1,
        "pps": 0.75,
        "efg": 44.4,
        "verdict": "Average",
        "percentile": 37,
        "subs": []
      },
      {
        "name": "Spot Up",
        "poss": 14,
        "timePct": 3.6,
        "pps": 0.857,
        "efg": 44.4,
        "verdict": "Average",
        "percentile": 36,
        "subs": [
          {
            "name": "Drives Right",
            "poss": 10,
            "timePct": 71.4,
            "pps": 1.0,
            "efg": 50.0
          },
          {
            "name": "Drives Left",
            "poss": 3,
            "timePct": 21.4,
            "pps": 0.667,
            "efg": 50.0
          },
          {
            "name": "Drives Straight",
            "poss": 1,
            "timePct": 7.1,
            "pps": 0.0,
            "efg": 0.0
          }
        ]
      },
      {
        "name": "P&R Ball Handler",
        "poss": 4,
        "timePct": 1.0,
        "pps": 0.5,
        "efg": 0.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Off Screen",
        "poss": 3,
        "timePct": 0.8,
        "pps": 1.333,
        "efg": 100.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Handoffs",
        "poss": 0,
        "timePct": 0.0,
        "pps": null,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotTypes": [
      {
        "name": "Jump Shot",
        "poss": 4,
        "timePct": 1.6,
        "pps": 0.0,
        "efg": 0.0,
        "verdict": null,
        "percentile": null,
        "subs": [
          {
            "name": "Catch and Shoot",
            "poss": 0,
            "timePct": 0.0,
            "pps": null,
            "efg": null,
            "subs": [
              {
                "name": "Guarded",
                "poss": 0,
                "timePct": 0.0,
                "pps": null,
                "efg": null
              },
              {
                "name": "Unguarded",
                "poss": 0,
                "timePct": 0.0,
                "pps": null,
                "efg": null
              }
            ]
          },
          {
            "name": "Dribble Jumper",
            "poss": 2,
            "timePct": 50.0,
            "pps": 0.0,
            "efg": 0.0,
            "subs": []
          },
          {
            "name": "Early Jumper",
            "poss": 0,
            "timePct": 0.0,
            "pps": null,
            "efg": null,
            "subs": []
          }
        ]
      },
      {
        "name": "At Rim",
        "poss": 220,
        "timePct": 87.6,
        "pps": 1.3,
        "efg": 65.0,
        "verdict": "Very Good",
        "percentile": 78,
        "subs": [
          {
            "name": "Layup",
            "poss": 149,
            "timePct": 67.7,
            "pps": 1.14,
            "efg": 57.0,
            "subs": []
          },
          {
            "name": "Dunk",
            "poss": 65,
            "timePct": 29.5,
            "pps": 1.75,
            "efg": 87.7,
            "subs": []
          },
          {
            "name": "Tip",
            "poss": 6,
            "timePct": 2.7,
            "pps": 0.33,
            "efg": 16.7,
            "subs": []
          }
        ]
      },
      {
        "name": "Runner",
        "poss": 8,
        "timePct": 3.2,
        "pps": 1.25,
        "efg": 62.5,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Hook",
        "poss": 14,
        "timePct": 5.6,
        "pps": 0.71,
        "efg": 35.7,
        "verdict": "Below Average",
        "percentile": 22,
        "subs": []
      }
    ],
    "shotZones": {
      "restrictedArea": {
        "volume": 90.2,
        "efg": 65.0,
        "poss": 220
      },
      "paint": {
        "volume": 9.0,
        "efg": 45.4,
        "poss": 22
      },
      "midrange": {
        "volume": 0.8,
        "efg": 0.0,
        "poss": 2
      },
      "beyondArc": {
        "volume": 0.0,
        "efg": null,
        "poss": 0
      }
    },
    "archetype": "Paint-Dominant 5",
    "analysis": [
      "Elite interior scorer: 62.8 eFG, 64.7 TS%, 122.4 ORtg on 24.9% usage.",
      "Top-tier glass on both ends (11.8 OR%, 26.3 DR%) plus rim protection (7.9 Blk%).",
      "Foul-prone (6.6 FC/40) and turnover-prone (16.0 TORate); operates exclusively inside (zero 3PT attempts)."
    ]
  },
  "woo": {
    "name": "Tyrone Marshall",
    "number": 24,
    "position": "PF",
    "primary_position": "PF",
    "year_abbr": "Sr",
    "year": "Senior",
    "height": "6-8",
    "weight": 215,
    "hometown": "Nashville, TN",
    "team": "George Washington",
    "season": "2025-26",
    "games": 32,
    "kenpom": {
      "minPct": 55.5,
      "ortg": 113.6,
      "possPct": 19.4,
      "shotsPct": 17.9,
      "efg": 57.1,
      "ts": 58.9,
      "orPct": 8.3,
      "drPct": 14.5,
      "aRate": 14.5,
      "toRate": 20.2,
      "blkPct": 3.7,
      "stlPct": 2.8,
      "fc40": 4.8,
      "fd40": 3.3,
      "ftRate": 38.2,
      "ft": {
        "made": 51,
        "att": 78,
        "pct": 0.654
      },
      "twoP": {
        "made": 85,
        "att": 146,
        "pct": 0.582
      },
      "threeP": {
        "made": 21,
        "att": 58,
        "pct": 0.362
      }
    },
    "playTypes": [
      {
        "name": "Spot Up",
        "poss": 60,
        "timePct": 19.9,
        "pps": 0.9,
        "efg": 50.0,
        "verdict": "Average",
        "percentile": 43,
        "subs": [
          {
            "name": "No Dribble Jumper",
            "poss": 31,
            "timePct": 51.7,
            "pps": 1.065,
            "efg": 53.2
          },
          {
            "name": "Drives Right",
            "poss": 16,
            "timePct": 26.7,
            "pps": 1.188,
            "efg": 72.2
          },
          {
            "name": "Drives Left",
            "poss": 10,
            "timePct": 16.7,
            "pps": 0.2,
            "efg": 0.0
          },
          {
            "name": "Drives Straight",
            "poss": 1,
            "timePct": 1.7,
            "pps": 0.0,
            "efg": 0.0
          },
          {
            "name": "Turnover",
            "poss": 2,
            "timePct": 3.3,
            "pps": 0.0,
            "efg": null
          }
        ]
      },
      {
        "name": "Transition",
        "poss": 55,
        "timePct": 18.3,
        "pps": 1.091,
        "efg": 66.7,
        "verdict": "Good",
        "percentile": 53,
        "subs": []
      },
      {
        "name": "Cut",
        "poss": 48,
        "timePct": 15.9,
        "pps": 1.0,
        "efg": 53.8,
        "verdict": "Below Average",
        "percentile": 23,
        "subs": []
      },
      {
        "name": "Miscellaneous Plays",
        "poss": 28,
        "timePct": 9.3,
        "pps": 0.429,
        "efg": 37.5,
        "verdict": "Average",
        "percentile": 36,
        "subs": []
      },
      {
        "name": "P&R Ball Handler",
        "poss": 27,
        "timePct": 9.0,
        "pps": 0.556,
        "efg": 31.3,
        "verdict": "Poor",
        "percentile": 14,
        "subs": []
      },
      {
        "name": "Offensive Rebounds (Put Backs)",
        "poss": 25,
        "timePct": 8.3,
        "pps": 1.04,
        "efg": 50.0,
        "verdict": "Average",
        "percentile": 33,
        "subs": []
      },
      {
        "name": "Post-Up",
        "poss": 23,
        "timePct": 7.6,
        "pps": 0.957,
        "efg": 50.0,
        "verdict": "Good",
        "percentile": 65,
        "subs": []
      },
      {
        "name": "Isolation",
        "poss": 12,
        "timePct": 4.0,
        "pps": 1.167,
        "efg": 50.0,
        "verdict": "Excellent",
        "percentile": 92,
        "subs": []
      },
      {
        "name": "P&R Roll Man",
        "poss": 11,
        "timePct": 3.7,
        "pps": 1.818,
        "efg": 95.0,
        "verdict": "Excellent",
        "percentile": 100,
        "subs": []
      },
      {
        "name": "Handoffs",
        "poss": 7,
        "timePct": 2.3,
        "pps": 1.714,
        "efg": 110.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Off Screen",
        "poss": 5,
        "timePct": 1.7,
        "pps": 1.4,
        "efg": 62.5,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotTypes": [
      {
        "name": "Jump Shot",
        "poss": 62,
        "timePct": 29.1,
        "pps": 1.05,
        "efg": 52.4,
        "verdict": "Very Good",
        "percentile": 75,
        "subs": [
          {
            "name": "Catch and Shoot",
            "poss": 52,
            "timePct": 83.9,
            "pps": 1.15,
            "efg": 57.7,
            "subs": [
              {
                "name": "Guarded",
                "poss": 23,
                "timePct": 44.2,
                "pps": 1.04,
                "efg": 52.2
              },
              {
                "name": "Unguarded",
                "poss": 29,
                "timePct": 55.8,
                "pps": 1.24,
                "efg": 62.1
              }
            ]
          },
          {
            "name": "Dribble Jumper",
            "poss": 8,
            "timePct": 12.9,
            "pps": 0.38,
            "efg": 18.8,
            "subs": []
          },
          {
            "name": "Early Jumper",
            "poss": 0,
            "timePct": 0.0,
            "pps": null,
            "efg": null,
            "subs": []
          }
        ]
      },
      {
        "name": "At Rim",
        "poss": 121,
        "timePct": 56.8,
        "pps": 1.22,
        "efg": 61.2,
        "verdict": "Good",
        "percentile": 64,
        "subs": [
          {
            "name": "Layup",
            "poss": 95,
            "timePct": 78.5,
            "pps": 1.14,
            "efg": 56.8,
            "subs": []
          },
          {
            "name": "Dunk",
            "poss": 22,
            "timePct": 18.2,
            "pps": 1.73,
            "efg": 86.4,
            "subs": []
          },
          {
            "name": "Tip",
            "poss": 4,
            "timePct": 3.3,
            "pps": 0.5,
            "efg": 25.0,
            "subs": []
          }
        ]
      },
      {
        "name": "Runner",
        "poss": 12,
        "timePct": 5.6,
        "pps": 0.83,
        "efg": 41.7,
        "verdict": "Good",
        "percentile": 57,
        "subs": []
      },
      {
        "name": "Hook",
        "poss": 18,
        "timePct": 8.5,
        "pps": 0.67,
        "efg": 33.3,
        "verdict": "Below Average",
        "percentile": 18,
        "subs": []
      }
    ],
    "shotZones": {
      "restrictedArea": {
        "volume": 57.3,
        "efg": 61.2,
        "poss": 121
      },
      "paint": {
        "volume": 14.2,
        "efg": 36.7,
        "poss": 30
      },
      "midrange": {
        "volume": 3.8,
        "efg": 18.8,
        "poss": 8
      },
      "beyondArc": {
        "volume": 24.6,
        "efg": 57.7,
        "poss": 52
      }
    },
    "archetype": "Efficient Two-Way Wing",
    "analysis": [
      "Knockdown shooter: 57.1 eFG, 58.9 TS% on 19.4% usage.",
      "Hits 58.2% from 2 and 36.2% from 3 on 58 attempts; high-volume 2PT efficiency stands out.",
      "Active off-ball defender (3.7 Blk%, 2.8 Stl%); 20.2 TORate is the one concern."
    ]
  },
  "gj": {
    "name": "Garrett Johnson",
    "number": 9,
    "position": "PF·SF",
    "primary_position": "PF",
    "year_abbr": "Jr",
    "year": "Junior",
    "height": "6-8",
    "weight": 220,
    "hometown": "Oakton, VA",
    "team": "George Washington",
    "season": "2025-26",
    "games": 29,
    "kenpom": {
      "minPct": 48.3,
      "ortg": 115.3,
      "possPct": 22.4,
      "shotsPct": 26.9,
      "efg": 50.4,
      "ts": 54.8,
      "orPct": 4.3,
      "drPct": 13.0,
      "aRate": 9.7,
      "toRate": 11.6,
      "blkPct": 0.7,
      "stlPct": 0.9,
      "fc40": 3.3,
      "fd40": 3.6,
      "ftRate": 27.7,
      "ft": {
        "made": 62,
        "att": 74,
        "pct": 0.838
      },
      "twoP": {
        "made": 55,
        "att": 107,
        "pct": 0.514
      },
      "threeP": {
        "made": 53,
        "att": 160,
        "pct": 0.331
      }
    },
    "playTypes": [
      {
        "name": "Spot Up",
        "poss": 140,
        "timePct": 42.2,
        "pps": 1.05,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": [
          {
            "name": "No Dribble Jumper",
            "poss": 83,
            "timePct": 59.3,
            "pps": 1.036,
            "efg": null
          },
          {
            "name": "Drives Right",
            "poss": 29,
            "timePct": 20.7,
            "pps": 1.172,
            "efg": null
          },
          {
            "name": "Drives Left",
            "poss": 25,
            "timePct": 17.9,
            "pps": 1.08,
            "efg": null
          },
          {
            "name": "Drives Straight",
            "poss": 2,
            "timePct": 1.4,
            "pps": 0.0,
            "efg": null
          },
          {
            "name": "Turnover",
            "poss": 1,
            "timePct": 0.7,
            "pps": 0.0,
            "efg": null
          }
        ]
      },
      {
        "name": "Transition",
        "poss": 45,
        "timePct": 13.6,
        "pps": 0.867,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": [
          {
            "name": "Ballhandler",
            "poss": 10,
            "timePct": 22.2,
            "pps": 1.5,
            "efg": null
          },
          {
            "name": "Right Wing",
            "poss": 9,
            "timePct": 20.0,
            "pps": 0.667,
            "efg": null
          },
          {
            "name": "Left Wing",
            "poss": 16,
            "timePct": 35.6,
            "pps": 0.625,
            "efg": null
          },
          {
            "name": "Trailer",
            "poss": 8,
            "timePct": 17.8,
            "pps": 0.625,
            "efg": null
          },
          {
            "name": "Leak Outs",
            "poss": 1,
            "timePct": 2.2,
            "pps": 2.0,
            "efg": null
          },
          {
            "name": "First Middle",
            "poss": 1,
            "timePct": 2.2,
            "pps": 1.0,
            "efg": null
          }
        ]
      },
      {
        "name": "P&R Ball Handler",
        "poss": 33,
        "timePct": 9.9,
        "pps": 0.939,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Cut",
        "poss": 33,
        "timePct": 9.9,
        "pps": 1.121,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Off Screen",
        "poss": 18,
        "timePct": 5.4,
        "pps": 1.278,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Handoffs",
        "poss": 15,
        "timePct": 4.5,
        "pps": 0.333,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Offensive Rebounds (Put Backs)",
        "poss": 15,
        "timePct": 4.5,
        "pps": 1.067,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Miscellaneous Plays",
        "poss": 13,
        "timePct": 3.9,
        "pps": 0.846,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Isolation",
        "poss": 10,
        "timePct": 3.0,
        "pps": 0.9,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "P&R Roll Man",
        "poss": 8,
        "timePct": 2.4,
        "pps": 1.125,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Post-Up",
        "poss": 2,
        "timePct": 0.6,
        "pps": 1.0,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotTypes": [
      {
        "name": "Jump Shot",
        "poss": 166,
        "timePct": 61.7,
        "pps": 0.99,
        "efg": 49.7,
        "verdict": "Good",
        "percentile": 63,
        "subs": [
          {
            "name": "Catch and Shoot",
            "poss": 117,
            "timePct": 70.5,
            "pps": 0.99,
            "efg": 49.6,
            "subs": [
              {
                "name": "Guarded",
                "poss": 70,
                "timePct": 59.8,
                "pps": 1.06,
                "efg": 52.9
              },
              {
                "name": "Unguarded",
                "poss": 47,
                "timePct": 40.2,
                "pps": 0.89,
                "efg": 44.7
              }
            ]
          },
          {
            "name": "Dribble Jumper",
            "poss": 48,
            "timePct": 28.9,
            "pps": 0.96,
            "efg": 47.9,
            "subs": []
          },
          {
            "name": "Early Jumper",
            "poss": 2,
            "timePct": 1.2,
            "pps": 1.5,
            "efg": 75.0,
            "subs": []
          }
        ]
      },
      {
        "name": "At Rim",
        "poss": 86,
        "timePct": 32.0,
        "pps": 1.05,
        "efg": 52.3,
        "verdict": "Below Average",
        "percentile": 29,
        "subs": [
          {
            "name": "Layup",
            "poss": 78,
            "timePct": 90.7,
            "pps": 1.03,
            "efg": 51.3,
            "subs": []
          },
          {
            "name": "Dunk",
            "poss": 5,
            "timePct": 5.8,
            "pps": 1.6,
            "efg": 80.0,
            "subs": []
          },
          {
            "name": "Tip",
            "poss": 3,
            "timePct": 3.5,
            "pps": 0.67,
            "efg": 33.3,
            "subs": []
          }
        ]
      },
      {
        "name": "Runner",
        "poss": 11,
        "timePct": 4.1,
        "pps": 0.91,
        "efg": 45.5,
        "verdict": "Very Good",
        "percentile": 69,
        "subs": []
      },
      {
        "name": "Hook",
        "poss": 6,
        "timePct": 2.2,
        "pps": 0.67,
        "efg": 33.3,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotZones": {
      "restrictedArea": {
        "volume": 31.9,
        "efg": 52.3,
        "poss": 86
      },
      "paint": {
        "volume": 6.3,
        "efg": 41.2,
        "poss": 17
      },
      "midrange": {
        "volume": 18.5,
        "efg": 49.0,
        "poss": 50
      },
      "beyondArc": {
        "volume": 43.3,
        "efg": 49.6,
        "poss": 117
      }
    },
    "archetype": "High-Volume Stretch 4",
    "analysis": [
      "High-usage scorer (22.4% Poss, 26.9% Shots) with 115.3 ORtg.",
      "Lives at the line: 83.8% FT shooter on 74 attempts, 27.7 FTRate.",
      "Lighter on the glass than his frame suggests (4.3 OR%, 13.0 DR%); offensive role is shot-creation, not interior work."
    ]
  },
  "gerald": {
    "name": "Gerald Drumgoole",
    "number": 5,
    "position": "SF",
    "primary_position": "SF",
    "year_abbr": "Sr",
    "year": "Senior",
    "height": "6-5",
    "weight": 210,
    "hometown": "Rochester, NY",
    "team": "George Washington",
    "season": "2024-25",
    "games": 33,
    "kenpom": {
      "minPct": 65.2,
      "ortg": 98.1,
      "possPct": 23.4,
      "shotsPct": 28.2,
      "efg": 44.7,
      "ts": 48.0,
      "orPct": 3.5,
      "drPct": 8.3,
      "aRate": 9.8,
      "toRate": 13.1,
      "blkPct": 1.0,
      "stlPct": 1.8,
      "fc40": 2.7,
      "fd40": 3.4,
      "ftRate": 27.7,
      "ft": {
        "made": 65,
        "att": 94,
        "pct": 0.691
      },
      "twoP": {
        "made": 51,
        "att": 120,
        "pct": 0.425
      },
      "threeP": {
        "made": 67,
        "att": 219,
        "pct": 0.306
      }
    },
    "playTypes": [
      {
        "name": "Spot Up",
        "poss": 171,
        "timePct": 39.1,
        "pps": 0.953,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": [
          {
            "name": "No Dribble Jumper",
            "poss": 120,
            "timePct": 70.2,
            "pps": 0.975,
            "efg": null
          },
          {
            "name": "Drives Right",
            "poss": 21,
            "timePct": 12.3,
            "pps": 1.143,
            "efg": null
          },
          {
            "name": "Drives Left",
            "poss": 26,
            "timePct": 15.2,
            "pps": 0.654,
            "efg": null
          },
          {
            "name": "Drives Straight",
            "poss": 4,
            "timePct": 2.3,
            "pps": 1.25,
            "efg": null
          }
        ]
      },
      {
        "name": "Transition",
        "poss": 73,
        "timePct": 16.7,
        "pps": 1.0,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": [
          {
            "name": "Ballhandler",
            "poss": 19,
            "timePct": 26.0,
            "pps": 0.684,
            "efg": null
          },
          {
            "name": "Right Wing",
            "poss": 20,
            "timePct": 27.4,
            "pps": 0.65,
            "efg": null
          },
          {
            "name": "Left Wing",
            "poss": 22,
            "timePct": 30.1,
            "pps": 1.364,
            "efg": null
          },
          {
            "name": "Trailer",
            "poss": 6,
            "timePct": 8.2,
            "pps": 1.333,
            "efg": null
          },
          {
            "name": "Leak Outs",
            "poss": 2,
            "timePct": 2.7,
            "pps": 0.5,
            "efg": null
          },
          {
            "name": "First Middle",
            "poss": 4,
            "timePct": 5.5,
            "pps": 2.0,
            "efg": null
          }
        ]
      },
      {
        "name": "P&R Ball Handler",
        "poss": 63,
        "timePct": 14.4,
        "pps": 0.492,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Off Screen",
        "poss": 32,
        "timePct": 7.3,
        "pps": 1.0,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Handoffs",
        "poss": 31,
        "timePct": 7.1,
        "pps": 0.387,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Isolation",
        "poss": 18,
        "timePct": 4.1,
        "pps": 0.944,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Cut",
        "poss": 17,
        "timePct": 3.9,
        "pps": 1.294,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Miscellaneous Plays",
        "poss": 15,
        "timePct": 3.4,
        "pps": 0.933,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Offensive Rebounds (Put Backs)",
        "poss": 13,
        "timePct": 3.0,
        "pps": 0.769,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Post-Up",
        "poss": 4,
        "timePct": 0.9,
        "pps": 0.0,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "P&R Roll Man",
        "poss": 0,
        "timePct": 0.0,
        "pps": null,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotTypes": [
      {
        "name": "Jump Shot",
        "poss": 232,
        "timePct": null,
        "pps": 0.89,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": [
          {
            "name": "Catch and Shoot",
            "poss": 179,
            "timePct": null,
            "pps": 0.96,
            "efg": null,
            "subs": [
              {
                "name": "Guarded",
                "poss": 120,
                "timePct": null,
                "pps": 0.68,
                "efg": null
              },
              {
                "name": "Unguarded",
                "poss": 59,
                "timePct": null,
                "pps": 1.53,
                "efg": null
              }
            ]
          },
          {
            "name": "Dribble Jumper",
            "poss": 54,
            "timePct": null,
            "pps": 0.67,
            "efg": null,
            "subs": []
          },
          {
            "name": "Early Jumper",
            "poss": 4,
            "timePct": null,
            "pps": 1.5,
            "efg": null,
            "subs": []
          }
        ]
      },
      {
        "name": "At Rim",
        "poss": 104,
        "timePct": null,
        "pps": 0.92,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": [
          {
            "name": "Layup",
            "poss": 98,
            "timePct": null,
            "pps": 0.92,
            "efg": null,
            "subs": []
          },
          {
            "name": "Dunk",
            "poss": 4,
            "timePct": null,
            "pps": 1.5,
            "efg": null,
            "subs": []
          },
          {
            "name": "Tip",
            "poss": 2,
            "timePct": null,
            "pps": 0.0,
            "efg": null,
            "subs": []
          }
        ]
      },
      {
        "name": "Runner",
        "poss": 8,
        "timePct": null,
        "pps": 0.5,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Hook",
        "poss": 1,
        "timePct": null,
        "pps": 0.0,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotZones": {
      "restrictedArea": {
        "volume": 29.7,
        "efg": null,
        "poss": 104
      },
      "paint": {
        "volume": 2.6,
        "efg": null,
        "poss": 9
      },
      "midrange": {
        "volume": 16.6,
        "efg": null,
        "poss": 58
      },
      "beyondArc": {
        "volume": 51.1,
        "efg": null,
        "poss": 179
      }
    },
    "archetype": "High-Volume Wing Scorer",
    "analysis": [
      "Featured offensive option (23.4% Poss, 28.2% Shots) at modest efficiency: 98.1 ORtg, 48.0 TS%.",
      "Volume 3PT shooter (219 attempts) at 30.6%, league average; FT shooting (69%) softens his TS%.",
      "Limited secondary impact: 9.8 ARate, 8.3 DR%, 1.8 Stl%; possessions live on his shotmaking."
    ]
  }
};
